import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/shared/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const NotoSana = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: [
    "latin",
    "cyrillic",
    "cyrillic-ext",
    "devanagari",
    "greek",
    "greek-ext",
    "latin-ext",
    "vietnamese",
  ],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Anime Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable} ${NotoSana.variable} antialiased p-2 font-poppins`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
